package Exceptions;

public class ArithmaticException {

	public static void main(String[] args) {
		
	try {
		
		int a = 10;
		int b = 0;
		System.out.println("test 0 cursor here");
		int c = a / b;
		int arr[] = new int[1];
		arr[5]= 10;
		System.out.println(arr[5]);
	}
	catch (Exception m) {
		System.out.println("Bhaiya arithmaatic exception hai");
	}
	catch(ArrayIndexOutOfBoundsException e) {
		
	}
		System.out.println("test 1 cursor here");
	}

}
